# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

In [215]:
#方法1
grades = [77, 85, 56, 90, 66]
S=0
for i in grades:
    S=S+i
MeanGrand=S/len(grades)

print(f'平均數：{MeanGrand}')

平均數：74.8


In [217]:
#方法2
import numpy as np
grades = [77, 85, 56, 90, 66]
average=np.average(grades)
Sum=np.sum(grades)

print(f'平均數：{average}')
print(f'總數：{Sum}')

平均數：74.8
總數：374


In [219]:
#方法3
GradesArray=np.array(grades)
print(f'平均數：{GradesArray.mean()}')
print(f'總數：{GradesArray.sum()}')

平均數：74.8
總數：374


### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

### 【示範】陣列導向

最大值

In [229]:
#方法1
GradesArray.max()

90

In [231]:
#方法2
Max=np.max(grades)
print(f'最大值：{Max}')

最大值：90


標準差

In [233]:
#方法1
GradesArray.std()

12.416118556135006

In [235]:
#方法2
Std=np.std(grades)
print(f'標準差：{Std}')

標準差：12.416118556135006


### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [241]:
prices = [1096.95, 596.95, 896.95]
USDtoTWD=[]
TWDPrice=0
USDTWD=31.71
for i in prices:
    TWDPrice=i*USDTWD
    USDtoTWD.append(TWDPrice)
print(USDtoTWD)

[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [30]:
prices = [1096.95, 596.95, 896.95]
prices_Array=np.array(prices)
prices_Array_TWD=prices_Array*31.71
print(prices_Array_TWD)

[34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [247]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [249]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])
weighted_grades=grades*weights
print(weighted_grades)

[17.  24.5 36. ]


### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [251]:
weighted_grades.sum()

77.5

### 【技巧】 一行完成成績計算

In [253]:
np.dot(grades,weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [261]:
A=np.array([0.7372234 , 0.6126442 , 0.27626397, 0.28984569, 0.4988311 ,
       0.42021495, 0.4515489 , 0.15328583, 0.93455268, 0.23537373,
       0.24761985, 0.41945762, 0.44871061, 0.66726833, 0.15622678,
       0.70315927, 0.98138833, 0.8233088 , 0.85394749, 0.14797509,
       0.32816167, 0.64607213, 0.96849395, 0.90799427, 0.19579351,
       0.35618479, 0.30311169, 0.32568614, 0.66885309, 0.67844806,
       0.18201376, 0.69592441, 0.11077285, 0.22884185, 0.29488536,
       0.90457337, 0.19872841, 0.38361489, 0.35731267, 0.76200102,
       0.92178147, 0.44190395, 0.07941469, 0.03253205, 0.44805018,
       0.38885104, 0.15473767, 0.55240742, 0.80182196, 0.70921062])

In [263]:
print(A)

[0.7372234  0.6126442  0.27626397 0.28984569 0.4988311  0.42021495
 0.4515489  0.15328583 0.93455268 0.23537373 0.24761985 0.41945762
 0.44871061 0.66726833 0.15622678 0.70315927 0.98138833 0.8233088
 0.85394749 0.14797509 0.32816167 0.64607213 0.96849395 0.90799427
 0.19579351 0.35618479 0.30311169 0.32568614 0.66885309 0.67844806
 0.18201376 0.69592441 0.11077285 0.22884185 0.29488536 0.90457337
 0.19872841 0.38361489 0.35731267 0.76200102 0.92178147 0.44190395
 0.07941469 0.03253205 0.44805018 0.38885104 0.15473767 0.55240742
 0.80182196 0.70921062]


### 【技巧】 檢查 A 的 `shape`

In [265]:
np.shape(A)

(50,)

In [267]:
A[0]

0.7372234

### 【技巧】 更改 A 的 shape

In [72]:
B=A.reshape(5,10)
print(B)

[[0.7372234  0.6126442  0.27626397 0.28984569 0.4988311  0.42021495
  0.4515489  0.15328583 0.93455268 0.23537373]
 [0.24761985 0.41945762 0.44871061 0.66726833 0.15622678 0.70315927
  0.98138833 0.8233088  0.85394749 0.14797509]
 [0.32816167 0.64607213 0.96849395 0.90799427 0.19579351 0.35618479
  0.30311169 0.32568614 0.66885309 0.67844806]
 [0.18201376 0.69592441 0.11077285 0.22884185 0.29488536 0.90457337
  0.19872841 0.38361489 0.35731267 0.76200102]
 [0.92178147 0.44190395 0.07941469 0.03253205 0.44805018 0.38885104
  0.15473767 0.55240742 0.80182196 0.70921062]]


In [273]:
np.shape(B)
B[0,0]

0.7372234

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [275]:
A.reshape(5,10)

array([[0.7372234 , 0.6126442 , 0.27626397, 0.28984569, 0.4988311 ,
        0.42021495, 0.4515489 , 0.15328583, 0.93455268, 0.23537373],
       [0.24761985, 0.41945762, 0.44871061, 0.66726833, 0.15622678,
        0.70315927, 0.98138833, 0.8233088 , 0.85394749, 0.14797509],
       [0.32816167, 0.64607213, 0.96849395, 0.90799427, 0.19579351,
        0.35618479, 0.30311169, 0.32568614, 0.66885309, 0.67844806],
       [0.18201376, 0.69592441, 0.11077285, 0.22884185, 0.29488536,
        0.90457337, 0.19872841, 0.38361489, 0.35731267, 0.76200102],
       [0.92178147, 0.44190395, 0.07941469, 0.03253205, 0.44805018,
        0.38885104, 0.15473767, 0.55240742, 0.80182196, 0.70921062]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [77]:
C=B.ravel()
print(C)

[0.7372234  0.6126442  0.27626397 0.28984569 0.4988311  0.42021495
 0.4515489  0.15328583 0.93455268 0.23537373 0.24761985 0.41945762
 0.44871061 0.66726833 0.15622678 0.70315927 0.98138833 0.8233088
 0.85394749 0.14797509 0.32816167 0.64607213 0.96849395 0.90799427
 0.19579351 0.35618479 0.30311169 0.32568614 0.66885309 0.67844806
 0.18201376 0.69592441 0.11077285 0.22884185 0.29488536 0.90457337
 0.19872841 0.38361489 0.35731267 0.76200102 0.92178147 0.44190395
 0.07941469 0.03253205 0.44805018 0.38885104 0.15473767 0.55240742
 0.80182196 0.70921062]


array([0.7372234 , 0.6126442 , 0.27626397, 0.28984569, 0.4988311 ,
       0.42021495, 0.4515489 , 0.15328583, 0.93455268, 0.23537373,
       0.24761985, 0.41945762, 0.44871061, 0.66726833, 0.15622678,
       0.70315927, 0.98138833, 0.8233088 , 0.85394749, 0.14797509,
       0.32816167, 0.64607213, 0.96849395, 0.90799427, 0.19579351,
       0.35618479, 0.30311169, 0.32568614, 0.66885309, 0.67844806,
       0.18201376, 0.69592441, 0.11077285, 0.22884185, 0.29488536,
       0.90457337, 0.19872841, 0.38361489, 0.35731267, 0.76200102,
       0.92178147, 0.44190395, 0.07941469, 0.03253205, 0.44805018,
       0.38885104, 0.15473767, 0.55240742, 0.80182196, 0.70921062])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [79]:

matrix = np.zeros((2, 3))
print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]]


### 【技巧】 都是 1 的 array

In [81]:
matrix = np.ones((3, 4))
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 【技巧】單位矩陣

In [83]:
I_5 = np.eye(5)
print(I_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 【技巧】給定範圍均勻生出 n 個點

In [91]:
n = 5          # 點的數量
low = [0, 0]  # 各維度的下限 (例如：X 軸從 0 開始，Y 軸從 0 開始)
high = [10, 10] # 各維度的上限 (例如：X 軸到 10 結束，Y 軸到 10 結束)
points = np.random.uniform(low=low, high=high, size=(n, len(low)))

print("生成的點矩陣：")
print(points)

生成的點矩陣：
[[2.67327573 1.52603435]
 [8.83739043 9.8735318 ]
 [0.79098446 4.85163031]
 [8.35097608 1.33605073]
 [5.45188015 2.58107025]]


In [277]:
# 1. 基本用法（預設 100 個數字）
arr1 = np.linspace(0, 10, num=100)
print(arr1)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

### 【技巧】`range` 的 array 版

就是 `arange`。

In [112]:
r = range(5)
print(list(r))  # [0, 1, 2, 3, 4]

arr = np.arange(1, 10, 0.2)
print(arr)

[0, 1, 2, 3, 4]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [106]:
A=np.array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [281]:
A=np.arange(10).reshape(2,5)


#A=np.array([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [287]:
np.sum(A,axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [289]:
np.sum(A,axis=1)

array([10, 35])

In [291]:
A.sum()

45

### 【提示】當然也有可能全部算

In [54]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [55]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [56]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [295]:
L = np.array([3, -2, -1, 5, 7, -3])
np.where(L>0,True,False)

array([ True, False, False,  True,  True, False])

In [297]:
import numpy as np
L = np.array([3, -2, -1, 5, 7, -3])
index=np.where(L>0)

# 直接帶入 index
result = L[index]
print(result)  # 輸出: [3 5 7]


[3 5 7]


除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [301]:
L[L>0]

array([3, 5, 7])

這有點強, 我們還可以一次到位!

In [64]:
import numpy as np
L = np.array([3, -2, -1, 5, 7, -3])
index=np.where(L>0)

# 直接帶入 index
result = L[index]
print(result)  # 輸出: [3 5 7]

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [158]:
D=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
D[4:8]

array([4, 5, 6, 7])

### 【技巧】2維陣列切法

記得先列後行!

In [311]:
arr = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
# : 表示選取所有的 row
# 1:3 表示選取 column 索引 1, 2的位置
result = arr[:, 1:3]

print(result)

[[1 2]
 [6 7]]


要所有的row, 切出行 1-3 位置。

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [313]:
arr = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
# 1:2 表示選取 row 索引 1 的位置
# : 表示選取所有的 column
result = arr[1,:]

print(result)
np.shape(result)

[5 6 7 8 9]


(5,)

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [319]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
zipped = zip(x, y)
zipped_list = list(zipped)

print(list(zipped_list))

[(1, 5), (2, 6), (3, 7), (4, 8)]


### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [321]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# 1. 建立 zip 迭代器
zipped = zip(x, y)

# 2. 將迭代器轉換為真正的 list 儲存起來（這樣資料才不會消耗掉就消失）
zipped_list = list(zipped)
print("打包後的結果：", zipped_list) 
# 輸出: [(1, 5), (2, 6), (3, 7), (4, 8)]

# 3. 使用儲存好的 zipped_list 進行解開 (Unzip)
P = zip(*zipped_list)

# 4. 因為 P 也是一個迭代器，直接 print(P) 只會顯示物件記憶體位置，必須轉成 list 顯示
print("解開後的結果：", list(P))
# 輸出: [(1, 2, 3, 4), (5, 6, 7, 8)]

打包後的結果： [(1, 5), (2, 6), (3, 7), (4, 8)]
解開後的結果： [(1, 2, 3, 4), (5, 6, 7, 8)]


In [341]:
zipped_list=np.array(zipped_list)
zipped_list[:,0]

array([1, 2, 3, 4])

In [343]:
zipped_list[0,:]

array([1, 5])